spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chocoboard?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver